### ISSUE TITLE
Move installation section to INSTALL.md

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/open-source-project-template#13]
Installation can be quite a long section, but only needs to be read once (ideally). Having it in the main readme hurts scan-ability and detracts from reading over usage and config instructions.

[The instructions](https://github.com/cfpb/open-source-project-template#installation) say an external file can be linked to, but perhaps this repo should set a precedence of having installation instructions in their own file like the contributing doc and changelog are? 

I'd suggest:

- Move all installation instructions to `INSTALL.md` in the project root directory.
- Simply have the readme list this for installation instructions:
```markdown
## Installation
Follow the instructions in [INSTALL](INSTALL.md).
```

**Comment by Scotchester** [comment]
:+1:
